// <auto-generated />
namespace Acunmedya_Travel_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Slider_Service_Destination : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Slider_Service_Destination));
        
        string IMigrationMetadata.Id
        {
            get { return "202504211456508_Slider_Service_Destination"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
