// <auto-generated />
namespace Acunmedya_Travel_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class UpdateServiceTable_sold_ticketandsold_ticketchangeNullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateServiceTable_sold_ticketandsold_ticketchangeNullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202505231640364_UpdateServiceTable_sold_ticket-and-sold_ticket-change-Nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
